import { loc } from "./i18n";

/**
 * Слова, которые склоняются при числе: «1 сделка · 2 сделки · 12 сделок».
 * Отдельно от S, потому что это не готовая строка, а три формы для f.plural.
 */
export const P = {
  deals: { ru: ["сделка", "сделки", "сделок"] as [string, string, string], uz: ["bitim", "bitim", "bitim"] as [string, string, string] },
  leads: { ru: ["лид", "лида", "лидов"] as [string, string, string], uz: ["lid", "lid", "lid"] as [string, string, string] },
  contacts: { ru: ["контакт", "контакта", "контактов"] as [string, string, string], uz: ["kontakt", "kontakt", "kontakt"] as [string, string, string] },
  stages: { ru: ["стадия", "стадии", "стадий"] as [string, string, string], uz: ["bosqich", "bosqich", "bosqich"] as [string, string, string] },
  employees: { ru: ["сотрудник", "сотрудника", "сотрудников"] as [string, string, string], uz: ["xodim", "xodim", "xodim"] as [string, string, string] },
  projects: { ru: ["проект", "проекта", "проектов"] as [string, string, string], uz: ["loyiha", "loyiha", "loyiha"] as [string, string, string] },
  tasks: { ru: ["задача", "задачи", "задач"] as [string, string, string], uz: ["vazifa", "vazifa", "vazifa"] as [string, string, string] },
  templates: { ru: ["шаблон", "шаблона", "шаблонов"] as [string, string, string], uz: ["shablon", "shablon", "shablon"] as [string, string, string] },
  channels: { ru: ["канал", "канала", "каналов"] as [string, string, string], uz: ["kanal", "kanal", "kanal"] as [string, string, string] },
  events: { ru: ["событие", "события", "событий"] as [string, string, string], uz: ["hodisa", "hodisa", "hodisa"] as [string, string, string] },
  pipelines: { ru: ["воронка", "воронки", "воронок"] as [string, string, string], uz: ["voronka", "voronka", "voronka"] as [string, string, string] },
  days: { ru: ["день", "дня", "дней"] as [string, string, string], uz: ["kun", "kun", "kun"] as [string, string, string] },
  cards: { ru: ["карточка", "карточки", "карточек"] as [string, string, string], uz: ["karta", "karta", "karta"] as [string, string, string] },
  departments: { ru: ["отдел", "отдела", "отделов"] as [string, string, string], uz: ["bo‘lim", "bo‘lim", "bo‘lim"] as [string, string, string] },
  modules: { ru: ["модуль", "модуля", "модулей"] as [string, string, string], uz: ["modul", "modul", "modul"] as [string, string, string] },
  people: { ru: ["человек", "человека", "человек"] as [string, string, string], uz: ["kishi", "kishi", "kishi"] as [string, string, string] },
  contracts: { ru: ["договор", "договора", "договоров"] as [string, string, string], uz: ["shartnoma", "shartnoma", "shartnoma"] as [string, string, string] },
  documents: { ru: ["документ", "документа", "документов"] as [string, string, string], uz: ["hujjat", "hujjat", "hujjat"] as [string, string, string] },
  folders: { ru: ["папка", "папки", "папок"] as [string, string, string], uz: ["papka", "papka", "papka"] as [string, string, string] },
  deadlines: { ru: ["дедлайн", "дедлайна", "дедлайнов"] as [string, string, string], uz: ["muddat", "muddat", "muddat"] as [string, string, string] },
  timelineEvents: { ru: ["событие", "события", "событий"] as [string, string, string], uz: ["hodisa", "hodisa", "hodisa"] as [string, string, string] },
  programs: { ru: ["программа", "программы", "программ"] as [string, string, string], uz: ["dastur", "dastur", "dastur"] as [string, string, string] },
  years: { ru: ["год", "года", "лет"] as [string, string, string], uz: ["yosh", "yosh", "yosh"] as [string, string, string] },
  universities: { ru: ["вуз", "вуза", "вузов"] as [string, string, string], uz: ["universitet", "universitet", "universitet"] as [string, string, string] },
  refusals: { ru: ["отказ", "отказа", "отказов"] as [string, string, string], uz: ["rad javobi", "rad javobi", "rad javobi"] as [string, string, string] },
};

/** Строки интерфейса. Пользовательский контент (заметки, задачи) не переводится. */
export const S = {
  nav: {
    dashboard: loc("Дашборд", "Boshqaruv paneli"),
    students: loc("Студенты", "Talabalar"),
    applications: loc("Заявки", "Arizalar"),
    documents: loc("Документы", "Hujjatlar"),
    tasks: loc("Задачи", "Vazifalar"),
    deadlines: loc("Дедлайны", "Muddatlar"),
    universities: loc("Каталог вузов", "Universitetlar katalogi"),
    finance: loc("Финансы", "Moliya"),
    team: loc("Сотрудники", "Xodimlar"),
    settings: loc("Настройки", "Sozlamalar"),
    collapse: loc("Свернуть меню", "Menyuni yig‘ish"),
    expand: loc("Развернуть меню", "Menyuni ochish"),
    pin: loc("Закрепить в меню", "Menyuga mahkamlash"),
    unpin: loc("Открепить", "Mahkamlashni bekor qilish"),
    customize: loc("Настроить меню", "Menyuni sozlash"),
    customizeTitle: loc("Разделы меню", "Menyu bo‘limlari"),
    customizeHint: loc(
      "Скройте лишнее и переставьте разделы стрелками — своё меню у каждого сотрудника.",
      "Kerak bo‘lmaganini yashiring va bo‘limlarni o‘qlar bilan qayta joylashtiring — har bir xodimda o‘z menyusi.",
    ),
    hideSection: loc("Скрыть раздел", "Bo‘limni yashirish"),
    showSection: loc("Показать раздел", "Bo‘limni ko‘rsatish"),
    hideItem: loc("Скрыть пункт", "Bandni yashirish"),
    showItem: loc("Показать пункт", "Bandni ko‘rsatish"),
    resetOrder: loc("Сбросить порядок", "Tartibni tiklash"),
  },

  common: {
    search: loc("Поиск контакта, сделки, вуза…", "Kontakt, bitim, universitet qidirish"),
    searchShort: loc("Поиск", "Qidiruv"),
    export: loc("Экспорт", "Eksport"),
    filters: loc("Фильтры", "Filtrlar"),
    all: loc("Все", "Barchasi"),
    reset: loc("Сбросить", "Tozalash"),
    cancel: loc("Отмена", "Bekor qilish"),
    delete: loc("Удалить", "O‘chirish"),
    add: loc("Добавить", "Qo‘shish"),
    rename: loc("Переименовать", "Nomini o‘zgartirish"),
    moveUp: loc("Выше", "Yuqoriga"),
    moveDown: loc("Ниже", "Pastga"),
    today: loc("Сегодня", "Bugun"),
    clear: loc("Очистить", "Tozalash"),
    pickDate: loc("Выбрать дату", "Sanani tanlash"),
    fullName: loc("ФИО", "F.I.Sh."),
    latinName: loc("Имя латиницей", "Ism lotin harflarida"),
    minutesShort: loc("мин", "daq"),
    hoursShort: loc("ч", "soat"),
    save: loc("Сохранить", "Saqlash"),
    done: loc("Готово", "Tayyor"),
    empty: loc("Пусто", "Bo‘sh"),
    nothingFound: loc("Ничего не найдено — попробуйте снять фильтры.", "Hech narsa topilmadi — filtrlarni olib tashlang."),
    noTasks: loc("Задач нет.", "Vazifalar yo‘q."),
    noApplications: loc("Заявок пока нет.", "Hozircha arizalar yo‘q."),
    perYear: loc("в год", "yiliga"),
    notSet: loc("не задан", "belgilanmagan"),
    notRequired: loc("не требуется", "talab qilinmaydi"),
    none: loc("нет", "yo‘q"),
    yes: loc("есть", "bor"),
    curator: loc("куратор", "kurator"),
    mail: loc("Почта", "Pochta"),
    notifications: loc("Уведомления", "Bildirishnomalar"),
    noNotifications: loc("Пока всё спокойно", "Hozircha hammasi tinch"),
    overdue: loc("просрочено", "kechikkan"),
    workspace: loc("Рабочее пространство", "Ish maydoni"),
    signInAs: loc("Войти как сотрудник", "Xodim sifatida kirish"),
    language: loc("Язык интерфейса", "Interfeys tili"),
    scopeTenant: loc("всё агентство", "butun agentlik"),
    scopeBranch: loc("свой филиал", "o‘z filiali"),
    scopeOwn: loc("только свои записи", "faqat o‘z yozuvlari"),
    accessDenied: loc("Раздел недоступен", "Bo‘lim mavjud emas"),
    notFoundTitle: loc("Запись не найдена", "Yozuv topilmadi"),
    notFoundHint: loc(
      "Её нет либо она вне вашей зоны видимости: система не показывает записи чужого агентства, филиала или коллеги.",
      "U mavjud emas yoki sizning ko‘rish doirangizdan tashqarida: tizim boshqa agentlik, filial yoki hamkasb yozuvlarini ko‘rsatmaydi.",
    ),
    toHome: loc("На главную", "Bosh sahifaga"),
    accessDeniedHint: loc(
      "У роли нет прав на этот модуль. Попросите директора агентства расширить доступ в разделе «Сотрудники».",
      "Bu rolda modulga huquq yo‘q. Agentlik direktoridan «Xodimlar» bo‘limida huquq berishini so‘rang.",
    ),
  },

  dashboard: {
    greeting: loc("Добрый день", "Xayrli kun"),
    date: loc("16 сентября 2026, среда", "2026-yil 16-sentabr, chorshanba"),
    activeApps: loc("в работе", "ishda"),
    weekDeadlines: loc("на неделе", "shu haftada"),
    newApplication: loc("Новая сделка", "Yangi bitim"),
    tileStudents: loc("Контакты в работе", "Ishdagi kontaktlar"),
    tileStudentsHint: loc("всего в базе", "bazada jami"),
    tileApps: loc("Сделки в воронке", "Voronkadagi bitimlar"),
    tileWithOffer: loc("с offer", "offer bilan"),
    tileOnVisa: loc("на визе", "vizada"),
    tileDeadlines: loc("Дедлайны ≤ 7 дней", "Muddatlar ≤ 7 kun"),
    tileNearest: loc("ближайший", "eng yaqini"),
    tileCalm: loc("всё спокойно", "hammasi joyida"),
    tileContracted: loc("Законтрактовано", "Shartnomalar summasi"),
    tilePaid: loc("оплачено", "to‘langan"),
    funnel: loc("Воронка сделок", "Bitimlar voronkasi"),
    openBoard: loc("Открыть доску", "Doskani ochish"),
    nearestDeadlines: loc("Ближайшие дедлайны", "Eng yaqin muddatlar"),
    allDeadlines: loc("Все дедлайны", "Barcha muddatlar"),
    myTasks: loc("Мои задачи", "Mening vazifalarim"),
    allTasks: loc("Все задачи", "Barcha vazifalar"),
    feed: loc("Лента агентства", "Agentlik lentasi"),
    important: loc("важно", "muhim"),
    spotlightEyebrow: loc("Подбор вузов", "Universitet tanlash"),
    spotlightTitle: loc(
      "Соберите шорт-лист по TOPIK, бюджету, городу и направлению — за один проход по каталогу.",
      "TOPIK, byudjet, shahar va yo‘nalish bo‘yicha qisqa ro‘yxatni bir o‘tishda tuzing.",
    ),
    spotlightCta: loc("Открыть каталог", "Katalogni ochish"),
    lostPeriod: loc("за 30 дней", "so‘nggi 30 kunda"),
    lostValue: loc("на сумму", "summasi"),
    lostCta: loc("Посмотреть", "Ko‘rish"),
  },

  students: {
    passport: loc("Паспорт", "Pasport"),
    title: loc("Студенты", "Talabalar"),
    inScope: loc("в вашей зоне видимости", "sizning ko‘rish doirangizda"),
    scopeLabel: loc("область доступа", "kirish doirasi"),
    add: loc("Добавить студента", "Talaba qo‘shish"),
    filterLead: loc("Лиды", "Lidlar"),
    filterActive: loc("В работе", "Ishda"),
    filterEnrolled: loc("Зачислены", "Qabul qilingan"),
    filterPaused: loc("На паузе", "To‘xtatilgan"),
    filterLost: loc("Потеряны", "Yo‘qotilgan"),
    allCurators: loc("Все кураторы", "Barcha kuratorlar"),
    anyTopik: loc("Любой TOPIK", "Istalgan TOPIK"),
    searchBase: loc("Поиск по базе", "Baza bo‘yicha qidiruv"),
    colStudent: loc("Студент", "Talaba"),
    colCity: loc("Город", "Shahar"),
    colProfile: loc("Профиль", "Profil"),
    colBudget: loc("Бюджет / год", "Byudjet / yil"),
    colGoal: loc("Цель", "Maqsad"),
    colCurator: loc("Куратор", "Kurator"),
    colDossier: loc("Досье", "Dosye"),
    colStatus: loc("Статус", "Holat"),
    needsGrant: loc("нужен грант", "grant kerak"),
    anyCity: loc("любой город", "istalgan shahar"),
    notChosen: loc("не выбрано", "tanlanmagan"),
    notDefined: loc("не определено", "aniqlanmagan"),
    applicationsShort: loc("заявок", "ariza"),
    call: loc("Позвонить", "Qo‘ng‘iroq"),
    write: loc("Написать", "Xat yozish"),
    pickUniversity: loc("Подобрать вуз", "Universitet tanlash"),
    birthDate: loc("Дата рождения", "Tug‘ilgan sana"),
    education: loc("Образование", "Ma’lumoti"),
    gradYear: loc("Год выпуска", "Bitirgan yili"),
    inBaseSince: loc("В базе с", "Bazada"),
    lastTouch: loc("Последний контакт", "Oxirgi aloqa"),
    portfolio: loc("Портфолио", "Portfolio"),
    topikValidUntil: loc("TOPIK действует до", "TOPIK amal qiladi"),
    noCertificate: loc("нет сертификата", "sertifikat yo‘q"),
    budgetPerYear: loc("Бюджет в год", "Yillik byudjet"),
    level: loc("Уровень", "Bosqich"),
    intake: loc("Набор", "Qabul"),
    cities: loc("Города", "Shaharlar"),
    fields: loc("Направления", "Yo‘nalishlar"),
    ownership: loc("Форма вуза", "Universitet shakli"),
    dorm: loc("Общежитие", "Yotoqxona"),
    dormNeeded: loc("нужно", "kerak"),
    dormNotNeeded: loc("не нужно", "kerak emas"),
    grant: loc("Грант", "Grant"),
    grantCritical: loc("критично", "juda muhim"),
    grantPreferred: loc("желательно", "ma’qul"),
    dossierTitle: loc("Досье документов", "Hujjatlar dosyesi"),
    verifiedOf: loc("проверено", "tekshirilgan"),
    applications: loc("Заявки", "Arizalar"),
    recommended: loc("Рекомендованные вузы", "Tavsiya etilgan universitetlar"),
    allUniversities: loc("Все вузы", "Barcha universitetlar"),
    relatedTasks: loc("Связанные задачи", "Bog‘liq vazifalar"),
    source: loc("источник", "manba"),
    fileMissing: loc("файл не загружен", "fayl yuklanmagan"),
    needsApostille: loc("нужен апостиль", "apostil kerak"),
    apostille: loc("апостиль", "apostil"),
  },

  applications: {
    title: loc("Заявки", "Arizalar"),
    count: loc("заявок", "ariza"),
    subtitle: loc(
      "воронка от первого звонка до вылета",
      "birinchi qo‘ng‘iroqdan jo‘nashgacha bo‘lgan voronka",
    ),
    allStages: loc("Все этапы", "Barcha bosqichlar"),
    collectingShort: loc("Сбор документов", "Hujjat yig‘ish"),
    submittedShort: loc("Поданные", "Topshirilgan"),
    visaShort: loc("На визе", "Vizada"),
    allIntakes: loc("Все наборы", "Barcha qabullar"),
    onlyUrgent: loc("Только срочные", "Faqat shoshilinch"),
    inSelection: loc("заявок в выборке", "tanlovdagi ariza"),
    dossier: loc("Досье", "Dosye"),
    onStage: loc("на этапе", "bosqichda"),
    studentCard: loc("Карточка студента", "Talaba kartasi"),
    nextStage: loc("Перевести на следующий этап", "Keyingi bosqichga o‘tkazish"),
    docsOfApplication: loc("Документы по заявке", "Ariza hujjatlari"),
    fitTitle: loc("Сходимость с требованиями вуза", "Universitet talablariga moslik"),
    universityCard: loc("Карточка вуза", "Universitet kartasi"),
    fullYearCost: loc("полная стоимость года", "yillik to‘liq narx"),
    tasksOfApplication: loc("Задачи по заявке", "Ariza vazifalari"),
    application: loc("Заявка", "Ariza"),
    priority: loc("Приоритет", "Muhimlik"),
    created: loc("Создана", "Yaratilgan"),
    deadline: loc("Дедлайн", "Muddat"),
    contract: loc("Договор", "Shartnoma"),
    paid: loc("Оплачено", "To‘langan"),
    university: loc("Вуз", "Universitet"),
    city: loc("Город", "Shahar"),
    program: loc("Программа", "Dastur"),
    yearPrice: loc("Стоимость года", "Yillik narx"),
    requiredTopik: loc("Требуемый TOPIK", "Talab qilinadigan TOPIK"),
    curatorNote: loc("Заметка куратора", "Kurator izohi"),
    student: loc("Студент", "Talaba"),
    intake: loc("набор", "qabul"),
  },

  documents: {
    title: loc("Документы", "Hujjatlar"),
    ofStudents: loc("студентов", "talabalar"),
    needAttention: loc("требуют внимания", "e’tibor talab qiladi"),
    upload: loc("Загрузить документ", "Hujjat yuklash"),
    uploadFile: loc("Загрузить файл", "Fayl yuklash"),
    allFolders: loc("Все папки", "Barcha papkalar"),
    tabProblem: loc("Требуют внимания", "E’tibor talab qiladi"),
    tabExpiring: loc("Истекает срок", "Muddati tugayapti"),
    searchStudent: loc("Поиск по студенту", "Talaba bo‘yicha qidiruv"),
    noFolders: loc("Папок нет", "Papkalar yo‘q"),
    dossierOf: loc("Досье", "Dosye"),
    verified: loc("проверено", "tekshirilgan"),
    updated: loc("обновлено", "yangilangan"),
    until: loc("до", "gacha"),
    request: loc("Запросить документ", "Hujjat so‘rash"),
    requestFor: loc("Запросить у студента", "Talabadan so‘rash"),
    requestHint: loc(
      "Пункт появится в досье со статусом «запрошен» и попадёт в историю контакта. Файл прикрепится, когда подключим хранилище.",
      "Band dosyeda «so‘ralgan» holatida paydo bo‘ladi va kontakt tarixiga tushadi. Fayl ombor ulangach biriktiriladi.",
    ),
    docKind: loc("Тип документа", "Hujjat turi"),
    student: loc("Студент", "Talaba"),
    noteForStudent: loc("Комментарий для истории", "Tarix uchun izoh"),
    markVerified: loc("Проверен", "Tekshirildi"),
    markRejected: loc("Вернуть", "Qaytarish"),
    markReceived: loc("Получен", "Qabul qilindi"),
    allRequested: loc("Все пункты чек-листа уже в досье", "Chek-ro‘yxatning barcha bandlari dosyeda"),
    storagePending: loc(
      "Загрузка файлов появится вместе с хранилищем документов",
      "Fayl yuklash hujjatlar ombori bilan birga paydo bo‘ladi",
    ),
  },

  tasks: {
    title: loc("Задачи", "Vazifalar"),
    inProgress: loc("в работе", "ishda"),
    subtitle: loc(
      "руководитель ставит задачу — исполнитель видит её у себя и в дедлайнах",
      "rahbar vazifa qo‘yadi — ijrochi uni o‘zida va muddatlarda ko‘radi",
    ),
    create: loc("Новая задача", "Yangi vazifa"),
    onlyMine: loc("Только мои", "Faqat meniki"),
    allAssignees: loc("Все исполнители", "Barcha ijrochilar"),
    overdue: loc("просрочено", "kechikkan"),
    highPriority: loc("высокий приоритет", "yuqori muhimlik"),
    taskTitle: loc("Что нужно сделать", "Nima qilish kerak"),
    assignee: loc("Исполнитель", "Ijrochi"),
    due: loc("Срок", "Muddat"),
    priority: loc("Приоритет", "Muhimlik"),
    priorityLow: loc("Низкий", "Past"),
    priorityNormal: loc("Обычный", "Oddiy"),
    priorityHigh: loc("Высокий", "Yuqori"),
  },

  deadlines: {
    title: loc("Дедлайны", "Muddatlar"),
    overdue: loc("просрочено", "kechikkan"),
    subtitle: loc(
      "собираются автоматически из заявок, документов и задач — вручную ничего не дублируется",
      "arizalar, hujjatlar va vazifalardan avtomatik yig‘iladi — qo‘lda takrorlash shart emas",
    ),
    toCalendar: loc("Открыть календарь", "Kalendarni ochish"),
    groupOverdue: loc("Просрочено", "Kechikkan"),
    groupToday: loc("Сегодня и завтра", "Bugun va ertaga"),
    groupWeek: loc("Ближайшие 7 дней", "Yaqin 7 kun"),
    groupMonth: loc("8–30 дней", "8–30 kun"),
    groupLater: loc("Позже", "Keyinroq"),
  },

  universities: {
    title: loc("Каталог вузов", "Universitetlar katalogi"),
    country: loc("Корея", "Koreya"),
    universities: loc("вузов", "universitet"),
    programs: loc("программ", "dastur"),
    exportShortlist: loc("Выгрузить шорт-лист", "Qisqa ro‘yxatni yuklash"),
    add: loc("Добавить вуз", "Universitet qo‘shish"),
    draftBanner: loc(
      "Этап 1: структура и фильтры. Карточки заполнены демо-данными и помечены как «черновик». На этапе 2 записи заполняются с официальных страниц вузов и файлов admission guideline, после сверки карточка получает статус «проверено» и дату источника.",
      "1-bosqich: tuzilma va filtrlar. Kartalar demo ma’lumotlar bilan to‘ldirilgan va «qoralama» deb belgilangan. 2-bosqichda ma’lumotlar universitetlarning rasmiy sahifalari va admission guideline fayllaridan olinadi, tekshiruvdan so‘ng karta «tekshirilgan» maqomini oladi.",
    ),
    pickForStudent: loc("Подобрать под студента", "Talaba uchun tanlash"),
    applyPreferences: loc("Фильтровать по профилю", "Profil bo‘yicha filtrlash"),
    preferencesHint: loc(
      "Профиль студента сортирует список и объясняет каждый вуз. Включите, чтобы жёстко отсечь неподходящие.",
      "Talaba profili ro‘yxatni saralaydi va har bir universitetni izohlaydi. Mos kelmaganlarni butunlay olib tashlash uchun yoqing.",
    ),
    chooseStudent: loc("— выбрать студента —", "— talabani tanlang —"),
    budget: loc("бюджет", "byudjet"),
    cityAny: loc("город любой", "shahar ixtiyoriy"),
    universityName: loc("Название вуза", "Universitet nomi"),
    city: loc("Город", "Shahar"),
    ownership: loc("Форма собственности", "Mulkchilik shakli"),
    field: loc("Направление", "Yo‘nalish"),
    degree: loc("Уровень обучения", "Ta’lim bosqichi"),
    studentTopik: loc("TOPIK студента", "Talabaning TOPIK darajasi"),
    studentIelts: loc("IELTS студента", "Talabaning IELTS bali"),
    budgetPerYear: loc("Бюджет на год", "Yillik byudjet"),
    intake: loc("Набор", "Qabul"),
    conditions: loc("Условия", "Shartlar"),
    hasDorm: loc("Есть общежитие", "Yotoqxona bor"),
    grantFrom: loc("Грант от 50%", "Grant 50% dan"),
    languageCenter: loc("Языковой центр", "Til markazi"),
    visaGradeA: loc("Визовый рейтинг A", "Viza reytingi A"),
    englishTaught: loc("Есть английский трек", "Ingliz tili treki bor"),
    deadlineSoon: loc("Дедлайн", "Muddat"),
    any: loc("Любой", "Istalgan"),
    notImportant: loc("Не важно", "Farqi yo‘q"),
    noCertificate: loc("Нет сертификата", "Sertifikat yo‘q"),
    upTo: loc("до", "gacha"),
    found: loc("Найдено", "Topildi"),
    sortedByMatch: loc("отсортировано по совпадению с профилем", "profil bilan moslikka ko‘ra saralangan"),
    draft: loc("черновик данных", "ma’lumot qoralamasi"),
    verified: loc("проверено", "tekshirilgan"),
    tuitionPerYear: loc("Обучение в год", "Yillik o‘qish"),
    dorm: loc("Общежитие", "Yotoqxona"),
    requirements: loc("Требования", "Talablar"),
    noResults: loc("Под эти условия вузов нет", "Bu shartlarga mos universitet yo‘q"),
    noResultsHint: loc(
      "Снимите часть фильтров — обычно первым мешает бюджет или уровень TOPIK.",
      "Ba’zi filtrlarni olib tashlang — odatda byudjet yoki TOPIK darajasi to‘sqinlik qiladi.",
    ),
    inCountry: loc("в стране", "mamlakatda"),
    noRank: loc("без рейтинга", "reytingsiz"),
    founded: loc("основан в", "tashkil etilgan"),
    compare: loc("Сравнить", "Solishtirish"),
    addToShortlist: loc("Добавить в шорт-лист", "Qisqa ro‘yxatga qo‘shish"),
    programsTitle: loc("Программы", "Dasturlar"),
    languageOfStudy: loc("язык", "til"),
    whoFits: loc("Кому из базы подходит", "Bazadan kimga mos keladi"),
    noFits: loc(
      "Подходящих студентов в вашей зоне видимости нет.",
      "Ko‘rish doirangizda mos talabalar yo‘q.",
    ),
    ourApplications: loc("Наши заявки в этот вуз", "Bu universitetga arizalarimiz"),
    bankBalance: loc("Счёт в банке", "Bankdagi hisob"),
    gradWithin: loc("Срок после выпуска", "Bitirgandan keyingi muddat"),
    notLimited: loc("не ограничен", "cheklanmagan"),
    yearsUpTo: loc("до", "gacha"),
    admissionFee: loc("Вступительный взнос", "Ariza to‘lovi"),
    scholarshipUpTo: loc("Грант", "Grant"),
    visaStatus: loc("Визовый статус", "Viza maqomi"),
    intakes: loc("Наборы", "Qabullar"),
    sourceTitle: loc("Источник данных", "Ma’lumot manbai"),
    status: loc("Статус", "Holat"),
    updatedAt: loc("Обновлено", "Yangilangan"),
    guideline: loc("Admission guideline", "Admission guideline"),
    notLinked: loc("не привязан", "biriktirilmagan"),
    sourceHint: loc(
      "На этапе 2 сюда подключается разбор официальной страницы вуза и PDF с правилами приёма: система сверяет цифры и ставит дату проверки.",
      "2-bosqichda bu yerga universitetning rasmiy sahifasi va qabul qoidalari PDF fayli ulanadi: tizim raqamlarni solishtirib, tekshiruv sanasini qo‘yadi.",
    ),
    exportCatalog: loc("Выгрузить каталог", "Katalogni yuklab olish"),
    colName: loc("Вуз", "Universitet"),
    colRank: loc("Рейтинг", "Reyting"),
    colTuition: loc("Обучение в год", "Yillik o‘qish"),
    colDorm: loc("Общежитие", "Yotoqxona"),
  },

  shortlist: {
    add: loc("В шорт-лист", "Qisqa ro‘yxatga"),
    added: loc("В шорт-листе", "Ro‘yxatda"),
    title: loc("Шорт-лист", "Qisqa ro‘yxat"),
    count: loc("в шорт-листе", "qisqa ro‘yxatda"),
    compare: loc("Сравнить", "Solishtirish"),
    clear: loc("Очистить", "Tozalash"),
    limit: loc("максимум 6 вузов", "eng ko‘pi 6 ta universitet"),
    empty: loc("Шорт-лист пуст", "Qisqa ro‘yxat bo‘sh"),
    emptyHint: loc(
      "Откройте каталог, отфильтруйте вузы под профиль студента и добавьте подходящие — здесь они встанут рядом для сравнения.",
      "Katalogni oching, universitetlarni talaba profiliga moslab filtrlang va mos kelganlarini qo‘shing — bu yerda ular yonma-yon solishtiriladi.",
    ),
    forStudent: loc("для студента", "talaba uchun"),
    compareTitle: loc("Сравнение вузов", "Universitetlarni solishtirish"),
    backToCatalog: loc("К каталогу", "Katalogga"),
    criterion: loc("Критерий", "Mezon"),
    verdict: loc("Вердикт подбора", "Tanlov xulosasi"),
    yearCost: loc("Полная стоимость года", "Yillik to‘liq narx"),
    englishTaught: loc("Программы на английском", "Ingliz tilidagi dasturlar"),
    deadline: loc("Дедлайн подачи", "Topshirish muddati"),
    noDeadline: loc("набор закрыт", "qabul yopilgan"),
    selectStudent: loc("Студент", "Talaba"),
    withoutStudent: loc("Без студента", "Talabasiz"),
  },

  finance: {
    title: loc("Финансы", "Moliya"),
    inWork: loc("в работе", "ishda"),
    subtitle: loc(
      "суммы договоров с семьями в сумах; стоимость обучения в вузе считается отдельно",
      "oilalar bilan shartnoma summalari so‘mda; universitet o‘qish narxi alohida hisoblanadi",
    ),
    exportRegistry: loc("Выгрузить реестр", "Reestrni yuklash"),
    contracted: loc("Законтрактовано", "Shartnomalar summasi"),
    paid: loc("Оплачено", "To‘langan"),
    ofContracts: loc("от суммы договоров", "shartnoma summasidan"),
    receivable: loc("Дебиторка", "Qarzdorlik"),
    closedWon: loc("Закрыто успешно", "Muvaffaqiyatli yopilgan"),
    received: loc("получено", "olingan"),
    byManager: loc("По менеджерам", "Menejerlar bo‘yicha"),
    contractsShort: loc("дог.", "shart."),
    outOf: loc("из", "dan"),
    contracts: loc("Договоры", "Shartnomalar"),
    colStage: loc("Этап", "Bosqich"),
    colRest: loc("Остаток", "Qoldiq"),
    rate: loc("курс", "kurs"),
  },

  team: {
    openCard: loc("Открыть карточку", "Kartani ochish"),
    status: loc("Статус", "Holat"),
    personal: loc("Личные данные", "Shaxsiy ma’lumotlar"),
    position: loc("Должность", "Lavozim"),
    fullName: loc("ФИО", "F.I.Sh."),
    birthDate: loc("День рождения", "Tug‘ilgan kun"),
    phoneWork: loc("Рабочий телефон", "Ish telefoni"),
    phonePersonal: loc("Второй номер", "Ikkinchi raqam"),
    hiredAt: loc("Принят на работу", "Ishga qabul qilingan"),
    department: loc("Подразделение", "Bo‘lim"),
    workdayToday: loc("Рабочий день сегодня", "Bugungi ish kuni"),
    title: loc("Сотрудники", "Xodimlar"),
    seats: loc("мест по тарифу", "tarif bo‘yicha o‘rin"),
    of: loc("из", "dan"),
    subtitle: loc(
      "роль определяет и права, и зону видимости данных",
      "rol ham huquqni, ham ma’lumot ko‘rish doirasini belgilaydi",
    ),
    invite: loc("Пригласить", "Taklif qilish"),
    inviteHint: loc(
      "Сотрудник появится в списке со статусом «приглашён» и займёт место по тарифу.",
      "Xodim «taklif qilingan» holati bilan ro‘yxatda paydo bo‘ladi.",
    ),
    active: loc("активен", "faol"),
    invited: loc("приглашён", "taklif qilingan"),
    suspended: loc("заблокирован", "bloklangan"),
    applicationsShort: loc("заявок", "ariza"),
    inSystemSince: loc("в системе с", "tizimda"),
    lastSeen: loc("был", "oxirgi marta"),
    matrix: loc("Матрица прав", "Huquqlar matritsasi"),
    role: loc("Роль", "Rol"),
    levelFull: loc("полный", "to‘liq"),
    levelEdit: loc("правка", "tahrir"),
    levelRead: loc("чтение", "o‘qish"),
    placeInCompany: loc("Место в компании", "Kompaniyadagi o‘rni"),
  },

  settings: {
    title: loc("Настройки агентства", "Agentlik sozlamalari"),
    seats: loc("мест", "o‘rin"),
    saveChanges: loc("Сохранить изменения", "O‘zgarishlarni saqlash"),
    addressTitle: loc("Адрес системы", "Tizim manzili"),
    addressHint: loc(
      "Каждое агентство работает на своём поддомене — сотрудники и клиенты видят только его.",
      "Har bir agentlik o‘z subdomenida ishlaydi — xodimlar va mijozlar faqat uni ko‘radi.",
    ),
    platformSubdomain: loc("Поддомен платформы", "Platforma subdomeni"),
    willOpenAt: loc("Система откроется по адресу", "Tizim shu manzilda ochiladi"),
    unavailable: loc("Недоступно", "Band"),
    ownDomain: loc("Собственный домен агентства", "Agentlikning o‘z domeni"),
    domainNotConnected: loc("домен не подключён", "domen ulanmagan"),
    domainVerified: loc("DNS проверен, сертификат выпущен", "DNS tekshirildi, sertifikat berildi"),
    domainPending: loc("ждём проверки DNS", "DNS tekshiruvi kutilmoqda"),
    domainCanConnect: loc(
      "можно подключить свой домен вместо поддомена",
      "subdomen o‘rniga o‘z domeningizni ulash mumkin",
    ),
    dnsTitle: loc("Что добавить в DNS домена агентства:", "Agentlik domeni DNS’iga qo‘shiladigan yozuvlar:"),
    tlsHint: loc(
      "Сертификат TLS выпускается автоматически после проверки записи.",
      "TLS sertifikati yozuv tekshirilgandan so‘ng avtomatik beriladi.",
    ),
    currentHost: loc("Текущий хост запроса", "Joriy so‘rov xosti"),
    isolation: loc("Изоляция данных", "Ma’lumot izolyatsiyasi"),
    isolationValue: loc(
      "строгая: запрос без совпадающего арендатора не видит ни одной записи",
      "qat’iy: mos ijarachisiz so‘rov birorta yozuvni ko‘rmaydi",
    ),
    rolesTitle: loc("Роли и доступы", "Rollar va huquqlar"),
    integrations: loc("Интеграции", "Integratsiyalar"),
    stage2: loc("этап 2", "2-bosqich"),
    agency: loc("Агентство", "Agentlik"),
    name: loc("Название", "Nomi"),
    legalName: loc("Юридическое лицо", "Yuridik shaxs"),
    monogram: loc("Монограмма", "Monogramma"),
    interfaceLanguage: loc("Язык интерфейса по умолчанию", "Standart interfeys tili"),
    currency: loc("Валюта договоров", "Shartnoma valyutasi"),
    usdRate: loc("Курс доллара", "Dollar kursi"),
    rateHint: loc(
      "Курс применяется только для пересчёта стоимости обучения: вузы публикуют цены в долларах, семья считает в сумах.",
      "Kurs faqat o‘qish narxini qayta hisoblash uchun ishlatiladi: universitetlar narxni dollarda e’lon qiladi, oila so‘mda hisoblaydi.",
    ),
    inSystemSince: loc("В системе с", "Tizimda"),
    plan: loc("Тариф", "Tarif"),
    seatsUsed: loc("рабочих мест занято", "ish o‘rni band"),
    branches: loc("Филиалы", "Filiallar"),
    addBranch: loc("Добавить филиал", "Filial qo‘shish"),
    branchName: loc("Название филиала", "Filial nomi"),
    seatsHint: loc(
      "Расширение тарифа — через поддержку: место освобождается, когда сотрудника блокируют.",
      "Tarifni kengaytirish — qo‘llab-quvvatlash orqali.",
    ),
  },

  integrations: {
    telegram: loc("Telegram-бот для лидов", "Lidlar uchun Telegram-bot"),
    telegramHint: loc("заявка из бота сразу в воронку", "botdan ariza to‘g‘ridan-to‘g‘ri voronkaga"),
    smtp: loc("Почта агентства (SMTP)", "Agentlik pochtasi (SMTP)"),
    smtpHint: loc("письма студентам с домена агентства", "talabalarga agentlik domenidan xatlar"),
    storage: loc("Хранилище документов", "Hujjatlar ombori"),
    storageHint: loc("S3-совместимое, с версиями файлов", "S3-mos, fayl versiyalari bilan"),
    catalog: loc("Импорт каталога вузов", "Universitetlar katalogini import qilish"),
    catalogHint: loc("разбор admission guideline", "admission guideline tahlili"),
  },

  crm: {
    leads: loc("Лиды", "Lidlar"),
    deals: loc("Сделки", "Bitimlar"),
    contacts: loc("Контакты", "Kontaktlar"),
    lead: loc("Лид", "Lid"),
    deal: loc("Сделка", "Bitim"),
    contact: loc("Контакт", "Kontakt"),
    newLead: loc("Новый лид", "Yangi lid"),
    newDeal: loc("Новая сделка", "Yangi bitim"),
    newContact: loc("Новый контакт", "Yangi kontakt"),
    convert: loc("Конвертировать", "Konvertatsiya qilish"),
    converted: loc("Конвертирован", "Konvertatsiya qilingan"),
    convertHint: loc(
      "Создаст контакт и первую сделку, лид закроется и останется в истории.",
      "Kontakt va birinchi bitim yaratiladi, lid yopiladi va tarixda qoladi.",
    ),
    source: loc("Источник", "Manba"),
    channel: loc("Канал", "Kanal"),
    comment: loc("Комментарий", "Izoh"),
    inWork: loc("в работе", "ishda"),
    junkReason: loc("Причина", "Sabab"),
    dealsOfContact: loc("Сделки контакта", "Kontakt bitimlari"),
    noDeals: loc("Сделок пока нет", "Hozircha bitimlar yo‘q"),
    duplicateFound: loc("Найден дубль", "Dublikat topildi"),
    duplicateByPhone: loc("по номеру телефона", "telefon raqami bo‘yicha"),
    duplicateByEmail: loc("по email", "email bo‘yicha"),
    duplicateByPassport: loc("по номеру паспорта", "pasport raqami bo‘yicha"),
    duplicateHint: loc(
      "Такой человек уже есть в системе. Новая запись не создаётся — обращение уходит в существующую карточку.",
      "Bunday odam tizimda bor. Yangi yozuv yaratilmaydi — murojaat mavjud kartaga tushadi.",
    ),
    openExisting: loc("Открыть карточку", "Kartani ochish"),
    checkDuplicate: loc("Проверить дубль", "Dublikatni tekshirish"),
    phone: loc("Телефон", "Telefon"),
    createdFromLead: loc("Создан из лида", "Liddan yaratilgan"),
    contactsTitle: loc("Контакты", "Kontaktlar"),
    contactsSubtitle: loc(
      "один человек — одна карточка: повторные обращения падают в её историю",
      "bir odam — bitta karta: takroriy murojaatlar uning tarixiga tushadi",
    ),
    junk: loc("Некачественный", "Sifatsiz"),
    backToLeads: loc("К лидам", "Lidlarga"),
    backToDeals: loc("К сделкам", "Bitimlarga"),
    backToContacts: loc("К контактам", "Kontaktlarga"),
    stage: loc("Стадия", "Bosqich"),
    edit: loc("Изменить", "O‘zgartirish"),
    mainFields: loc("Основные поля", "Asosiy maydonlar"),
    contract: loc("Договор", "Shartnoma"),
    paid: loc("Оплачено", "To‘langan"),
    idle: loc("завис", "qotib qoldi"),
    idleDays: loc("дней без движения", "kun harakatsiz"),
    stalePreset: loc("Зависшие", "Qotib qolganlar"),
    owner: loc("Ответственный", "Mas’ul"),
  },

  pipelines: {
    title: loc("Воронки", "Voronkalar"),
    subtitle: loc(
      "стадии, их порядок и цвета — то, как агентство видит свою работу",
      "bosqichlar, tartibi va ranglari — agentlik ishini qanday ko‘rishi",
    ),
    stages: loc("Стадии", "Bosqichlar"),
    rename: loc("Название стадии", "Bosqich nomi"),
    color: loc("Цвет", "Rang"),
    hexCode: loc("Код цвета", "Rang kodi"),
    editStage: loc("Изменить стадию", "Bosqichni o‘zgartirish"),
    cardView: loc("Карточка просмотра", "Ko‘rish kartasi"),
    cardViewHint: loc(
      "Какие поля показывать на карточке канбана и в каком порядке.",
      "Kanban kartasida qaysi maydonlar va qanday tartibda ko‘rsatilsin.",
    ),
    fieldPhone: loc("Телефон", "Telefon"),
    fieldSource: loc("Источник", "Manba"),
    fieldComment: loc("Комментарий", "Izoh"),
    fieldUniversity: loc("Вуз", "Universitet"),
    fieldProgram: loc("Программа", "Dastur"),
    fieldIntake: loc("Набор", "Qabul"),
    fieldDossier: loc("Готовность досье", "Dosye tayyorligi"),
    fieldAmount: loc("Сумма договора", "Shartnoma summasi"),
    fieldDeadline: loc("Дедлайн", "Muddat"),
    fieldOwner: loc("Ответственный", "Mas’ul"),
    dragHint: loc("Перетащите карточку на другую стадию", "Kartani boshqa bosqichga torting"),
    pipeline: loc("Воронка", "Voronka"),
    viewKanban: loc("Канбан", "Kanban"),
    viewList: loc("Список", "Ro‘yxat"),
    moved: loc("Карточка перенесена", "Karta ko‘chirildi"),
    stageHint: loc("Подсказка", "Maslahat"),
    stageFinal: loc("Финальная стадия", "Yakuniy bosqich"),
    finalNone: loc("Обычная", "Oddiy"),
    finalWon: loc("Успех", "Muvaffaqiyat"),
    finalLost: loc("Провал", "Muvaffaqiyatsiz"),
    finalHint: loc(
      "Финальных стадий две на воронку: успех и провал. Они закрывают сделку и не занимают колонку на доске.",
      "Har voronkada ikkita yakuniy bosqich: muvaffaqiyat va muvaffaqiyatsizlik.",
    ),
    addStage: loc("Добавить стадию", "Bosqich qo‘shish"),
    newStage: loc("Новая стадия", "Yangi bosqich"),
    removeStage: loc("Удалить стадию", "Bosqichni o‘chirish"),
    stageInUse: loc("На стадии есть карточки — сначала перенесите их", "Bosqichda kartalar bor — avval ularni ko‘chiring"),
    addPipeline: loc("Новая воронка", "Yangi voronka"),
    removePipeline: loc("Удалить воронку", "Voronkani o‘chirish"),
    pipelineName: loc("Название воронки", "Voronka nomi"),
    makeDefault: loc("Сделать основной", "Asosiy qilish"),
    isDefault: loc("Основная", "Asosiy"),
    forLeads: loc("Для лидов", "Lidlar uchun"),
    forDeals: loc("Для сделок", "Bitimlar uchun"),
    order: loc("Порядок", "Tartib"),
  },

  channels: {
    title: loc("Каналы продаж", "Sotuv kanallari"),
    subtitle: loc(
      "откуда приходят обращения: каждое новое попадает в лиды",
      "murojaatlar qayerdan keladi: har biri lidlarga tushadi",
    ),
    connected: loc("Подключён", "Ulangan"),
    pending: loc("Ожидает подключения", "Ulanish kutilmoqda"),
    off: loc("Отключён", "O‘chirilgan"),
    connect: loc("Подключить", "Ulash"),
    disconnect: loc("Отключить", "O‘chirish"),
    perMonth: loc("в месяц", "oyiga"),
    instagram: loc("Instagram Direct", "Instagram Direct"),
    telegram: loc("Telegram-бот", "Telegram-bot"),
    email: loc("Почта агентства", "Agentlik pochtasi"),
    phone: loc("Телефония", "Telefoniya"),
    stage2: loc(
      "Интерфейс подключения готов; обмен сообщениями включается на этапе интеграций.",
      "Ulanish interfeysi tayyor; xabar almashish integratsiya bosqichida yoqiladi.",
    ),
  },

  timeline: {
    title: loc("История", "Tarix"),
    tabActivity: loc("Дело", "Ish"),
    tabComment: loc("Комментарий", "Izoh"),
    tabMessage: loc("Сообщение", "Xabar"),
    tabTask: loc("Задача", "Vazifa"),
    tabTelegram: loc("Telegram", "Telegram"),
    tabMore: loc("Ещё", "Yana"),
    placeholder: loc("Что нужно сделать", "Nima qilish kerak"),
    add: loc("Добавить", "Qo‘shish"),
    done: loc("Выполнено", "Bajarildi"),
    dueTo: loc("Сделать до", "Bajarish muddati"),
    empty: loc("Событий пока нет", "Hozircha hodisalar yo‘q"),
  },

  projects: {
    title: loc("Проекты", "Loyihalar"),
    members: loc("Участники", "Ishtirokchilar"),
    manager: loc("Руководитель", "Rahbar"),
    due: loc("Срок", "Muddat"),
    tasksInProject: loc("задач в проекте", "loyihadagi vazifa"),
    statusActive: loc("Активен", "Faol"),
    statusDone: loc("Завершён", "Yakunlangan"),
    statusPaused: loc("На паузе", "To‘xtatilgan"),
    reports: loc("Отчёты", "Hisobotlar"),
    templates: loc("Шаблоны", "Shablonlar"),
    checklist: loc("Чек-лист", "Ro‘yxat"),
    useTemplate: loc("Создать по шаблону", "Shablon bo‘yicha yaratish"),
    completed: loc("выполнено", "bajarilgan"),
    overdueTasks: loc("просрочено", "kechikkan"),
  },

  structure: {
    title: loc("Структура компании", "Kompaniya tuzilmasi"),
    subtitle: loc(
      "подразделения и руководители; сотрудника можно перенести в другой отдел",
      "bo‘limlar va rahbarlar; xodimni boshqa bo‘limga ko‘chirish mumkin",
    ),
    head: loc("Руководитель", "Rahbar"),
    employees: loc("сотрудников", "xodim"),
    moveHere: loc("Перенести сюда", "Bu yerga ko‘chirish"),
    noHead: loc("Руководитель не назначен", "Rahbar tayinlanmagan"),
    setHead: loc("Назначить руководителя", "Rahbar tayinlash"),
    subordinates: loc("Подчинённые", "Bo‘ysunuvchilar"),
    noChildren: loc("нет отделов в подчинении", "bo‘ysunuvchi bo‘limlar yo‘q"),
    totalEmployees: loc("Всего сотрудников", "Jami xodimlar"),
    inDepartment: loc("В отделе", "Bo‘limda"),
    searchPerson: loc("Найти по имени или должности", "Ism yoki lavozim bo‘yicha qidirish"),
    noPeople: loc("Никого не найдено", "Hech kim topilmadi"),
    findMe: loc("Найти меня", "Meni topish"),
    addDepartment: loc("Добавить отдел", "Bo‘lim qo‘shish"),
    name: loc("Название", "Nomi"),
    parent: loc("Входит в", "Tarkibida"),
    root: loc("Компания", "Kompaniya"),
    dragHint: loc(
      "Сотрудника можно перетащить из списка на карточку отдела — перевод попадёт в его историю.",
      "Xodimni ro‘yxatdan bo‘lim kartasiga tortish mumkin — ko‘chirish tarixga tushadi.",
    ),
    addSub: loc("Добавить подразделение внутрь", "Ichkariga bo‘lim qo‘shish"),
    renameDepartment: loc("Переименовать подразделение", "Bo‘lim nomini o‘zgartirish"),
    removeDepartment: loc("Удалить подразделение", "Bo‘limni o‘chirish"),
    removeHint: loc(
      "Вложенные отделы и сотрудники поднимутся на уровень выше — никто не потеряется.",
      "Ichki bo‘limlar va xodimlar yuqori darajaga ko‘tariladi.",
    ),
    addPerson: loc("Добавить сотрудника", "Xodim qo‘shish"),
    addPersonHint: loc(
      "Сотрудник переедет сюда из своего подразделения; история перевода сохранится.",
      "Xodim bu yerga ko‘chiriladi; ko‘chirish tarixi saqlanadi.",
    ),
    removePerson: loc("Вывести из подразделения", "Bo‘limdan chiqarish"),
    unassigned: loc("Вне структуры", "Tuzilmadan tashqarida"),
    unassignedHint: loc(
      "Эти сотрудники не числятся ни в одном подразделении — перетащите их на нужный отдел.",
      "Bu xodimlar hech qaysi bo‘limda emas — kerakli bo‘limga torting.",
    ),
    rootLocked: loc("Компанию удалить нельзя", "Kompaniyani o‘chirib bo‘lmaydi"),
  },

  workday: {
    start: loc("Начать рабочий день", "Ish kunini boshlash"),
    end: loc("Завершить рабочий день", "Ish kunini yakunlash"),
    breakStart: loc("Перерыв", "Tanaffus"),
    breakEnd: loc("Вернуться к работе", "Ishga qaytish"),
    endShort: loc("Завершить", "Yakunlash"),
    breakEndShort: loc("Вернуться", "Qaytish"),
    working: loc("Рабочий день идёт", "Ish kuni davom etmoqda"),
    onBreak: loc("Перерыв", "Tanaffus"),
    notStarted: loc("Рабочий день не начат", "Ish kuni boshlanmagan"),
    startedAt: loc("Начат в", "Boshlandi"),
    todayTotal: loc("Сегодня отработано", "Bugun ishlangan"),
    breakTotal: loc("Перерывы за день", "Kunlik tanaffuslar"),
    theme: loc("Тема оформления", "Mavzu"),
    myProfile: loc("Мой профиль", "Mening profilim"),
    logout: loc("Выйти", "Chiqish"),
  },

  staffReports: {
    title: loc("Отчётность сотрудников", "Xodimlar hisoboti"),
    subtitle: loc(
      "часы считаются из отметок «начать» и «завершить рабочий день»",
      "soatlar «boshlash» va «yakunlash» belgilaridan hisoblanadi",
    ),
    employee: loc("Сотрудник", "Xodim"),
    days: loc("Дней", "Kunlar"),
    hours: loc("Часов", "Soat"),
    average: loc("Средний день", "O‘rtacha kun"),
    breaks: loc("Перерывы", "Tanaffuslar"),
    late: loc("Опозданий", "Kechikishlar"),
    today: loc("Сегодня", "Bugun"),
    week: loc("Неделя", "Hafta"),
    month: loc("Месяц", "Oy"),
    stillWorking: loc("на работе", "ishda"),
    noData: loc("Отметок пока нет", "Belgilar yo‘q"),
    openReport: loc("Открыть отчётность", "Hisobotni ochish"),
  },

  calendar: {
    title: loc("Календарь", "Kalendar"),
    subtitle: loc(
      "встречи сотрудника и сроки из сделок, документов и задач в одном месте",
      "xodim uchrashuvlari va bitim, hujjat, vazifa muddatlari bir joyda",
    ),
    day: loc("День", "Kun"),
    week: loc("Неделя", "Hafta"),
    month: loc("Месяц", "Oy"),
    today: loc("Сегодня", "Bugun"),
    add: loc("Добавить", "Qo‘shish"),
    eventTitle: loc("Что за событие", "Hodisa nomi"),
    date: loc("Дата", "Sana"),
    kind: loc("Тип", "Turi"),
    from: loc("Начало", "Boshlanishi"),
    to: loc("Конец", "Tugashi"),
    onDay: loc("На", "Sana"),
    empty: loc("На этот день ничего не запланировано", "Bu kunga hech narsa rejalashtirilmagan"),
    kindMeeting: loc("Встреча", "Uchrashuv"),
    kindCall: loc("Звонок", "Qo‘ng‘iroq"),
    kindInterview: loc("Интервью", "Suhbat"),
    kindPersonal: loc("Личное", "Shaxsiy"),
    myOnly: loc("Только мои", "Faqat meniki"),
    deadline: loc("Дедлайн", "Muddat"),
    task: loc("Задача", "Vazifa"),
    activity: loc("Дело", "Ish"),
    time: loc("Время", "Vaqt"),
    timeFrom: loc("с", "dan"),
    timeTo: loc("до", "gacha"),
    timeHint: loc("9 · 930 · 21:15", "9 · 930 · 21:15"),
    newEvent: loc("Новое дело", "Yangi ish"),
  },

  admin: {
    title: loc("Администрирование", "Boshqaruv"),
    users: loc("Пользователи", "Foydalanuvchilar"),
    permissions: loc("Права доступа", "Kirish huquqlari"),
    portal: loc("Настройки портала", "Portal sozlamalari"),
    permissionsCount: loc("Роли и разделы", "Rollar va bo‘limlar"),
    crmSettings: loc("Настройки CRM", "CRM sozlamalari"),
    permissionsHint: loc(
      "Матрица прав редактируется прямо здесь: изменения сразу влияют на меню и данные сотрудников.",
      "Huquqlar matritsasi shu yerda tahrirlanadi: o‘zgarishlar darhol menyuga ta’sir qiladi.",
    ),
    module: loc("Раздел", "Bo‘lim"),
    scope: loc("Зона видимости", "Ko‘rish doirasi"),
    invite: loc("Пригласить", "Taklif qilish"),
    inviteHint: loc(
      "Сотрудник появится в списке со статусом «приглашён» и займёт место по тарифу.",
      "Xodim «taklif qilingan» holati bilan ro‘yxatda paydo bo‘ladi.",
    ),
    block: loc("Заблокировать", "Bloklash"),
    unblock: loc("Разблокировать", "Blokdan chiqarish"),
    changeRole: loc("Сменить роль", "Rolni o‘zgartirish"),
    seats: loc("мест по тарифу", "tarif bo‘yicha o‘rin"),
    auditLog: loc("Журнал действий", "Harakatlar jurnali"),
    subtitle: loc(
      "Один вход во все настройки портала: воронки, каналы, права, тариф и домен.",
      "Portal sozlamalariga yagona kirish: voronkalar, kanallar, huquqlar, tarif va domen.",
    ),
    section: loc("Раздел настроек", "Sozlamalar bo‘limi"),
    lock: loc("Закрыть настройки", "Sozlamalarni yopish"),
    passcode: loc("Код входа", "Kirish kodi"),
    passcodeHint: loc(
      "От 4 до 12 цифр. Код знает только тот, кто ведёт портал; сотрудники настроек не видят вовсе.",
      "4 dan 12 gacha raqam. Kodni faqat portalni yurituvchi biladi.",
    ),
    changePasscode: loc("Сменить код", "Kodni o‘zgartirish"),
    demo: loc("Демо-режим", "Demo rejim"),
    demoHint: loc(
      "Показ портала: агентство и сотрудник, от лица которого вы смотрите систему.",
      "Portalni ko‘rsatish: agentlik va siz kimning nomidan ko‘rayotganingiz.",
    ),
    groupCrm: loc("CRM", "CRM"),
    groupPeople: loc("Люди и доступы", "Odamlar va huquqlar"),
    groupPortal: loc("Портал", "Portal"),
    structure: loc("Оргструктура", "Tashkiliy tuzilma"),
    structureHint: loc(
      "подразделения, руководители, кто кому подчиняется",
      "bo‘limlar, rahbarlar, kim kimga bo‘ysunadi",
    ),
  },

  adminLock: {
    title: loc("Настройки портала", "Portal sozlamalari"),
    hint: loc(
      "Раздел закрыт кодом: здесь меняются воронки, права и тариф. Сотрудникам он не нужен и не виден.",
      "Bo‘lim kod bilan yopilgan: bu yerda voronkalar, huquqlar va tarif o‘zgaradi.",
    ),
    placeholder: loc("Код", "Kod"),
    enter: loc("Войти", "Kirish"),
    wrong: loc("Неверный код", "Kod noto‘g‘ri"),
  },

  edition: {
    notIncluded: loc(
      "Модуль не входит в вашу версию продукта. Он включается вместе с версией CRM — вместе со всей работой по студентам: заявки, документы, задачи и сроки.",
      "Modul sizning mahsulot versiyangizga kirmaydi. U CRM versiyasi bilan birga ochiladi: arizalar, hujjatlar, vazifalar va muddatlar.",
    ),
    yourEdition: loc("Ваша версия", "Sizning versiyangiz"),
    upgrade: loc("Подключить версию", "Versiyani ulash"),
    edition: loc("Версия продукта", "Mahsulot versiyasi"),
    includedModules: loc("модулей включено", "modul yoqilgan"),
    roadmap: loc("Дорожная карта", "Yo‘l xaritasi"),
    current: loc("текущая", "joriy"),
    next: loc("следующая", "keyingi"),
    later: loc("позже", "keyinroq"),
  },

  plans: {
    trial: loc("Пробный период", "Sinov davri"),
    standard: loc("Standard", "Standard"),
    pro: loc("Pro", "Pro"),
    enterprise: loc("Enterprise", "Enterprise"),
  },
};
