import { loc } from "./i18n";

/**
 * Слова, которые склоняются при числе: «1 сделка · 2 сделки · 12 сделок».
 * Отдельно от S, потому что это не готовая строка, а три формы для f.plural.
 */
export const P = {
  deals: { ru: ["сделка", "сделки", "сделок"] as [string, string, string], uz: ["bitim", "bitim", "bitim"] as [string, string, string] },
  leads: { ru: ["лид", "лида", "лидов"] as [string, string, string], uz: ["lid", "lid", "lid"] as [string, string, string] },
  contacts: { ru: ["контакт", "контакта", "контактов"] as [string, string, string], uz: ["kontakt", "kontakt", "kontakt"] as [string, string, string] },
  stages: { ru: ["стадия", "стадии", "стадий"] as [string, string, string], uz: ["bosqich", "bosqich", "bosqich"] as [string, string, string] },
  employees: { ru: ["сотрудник", "сотрудника", "сотрудников"] as [string, string, string], uz: ["xodim", "xodim", "xodim"] as [string, string, string] },
  projects: { ru: ["проект", "проекта", "проектов"] as [string, string, string], uz: ["loyiha", "loyiha", "loyiha"] as [string, string, string] },
  tasks: { ru: ["задача", "задачи", "задач"] as [string, string, string], uz: ["vazifa", "vazifa", "vazifa"] as [string, string, string] },
  templates: { ru: ["шаблон", "шаблона", "шаблонов"] as [string, string, string], uz: ["shablon", "shablon", "shablon"] as [string, string, string] },
  channels: { ru: ["канал", "канала", "каналов"] as [string, string, string], uz: ["kanal", "kanal", "kanal"] as [string, string, string] },
  pipelines: { ru: ["воронка", "воронки", "воронок"] as [string, string, string], uz: ["voronka", "voronka", "voronka"] as [string, string, string] },
};

/** Строки интерфейса. Пользовательский контент (заметки, задачи) не переводится. */
export const S = {
  nav: {
    dashboard: loc("Дашборд", "Boshqaruv paneli"),
    students: loc("Студенты", "Talabalar"),
    applications: loc("Заявки", "Arizalar"),
    documents: loc("Документы", "Hujjatlar"),
    tasks: loc("Задачи", "Vazifalar"),
    deadlines: loc("Дедлайны", "Muddatlar"),
    universities: loc("Каталог вузов", "Universitetlar katalogi"),
    finance: loc("Финансы", "Moliya"),
    team: loc("Сотрудники", "Xodimlar"),
    settings: loc("Настройки", "Sozlamalar"),
    groupWork: loc("Операционка", "Kundalik ish"),
    groupBase: loc("База знаний", "Bilimlar bazasi"),
    groupAdmin: loc("Агентство", "Agentlik"),
  },

  common: {
    search: loc("Поиск студента, заявки, вуза…", "Talaba, ariza, universitet qidirish"),
    searchShort: loc("Поиск", "Qidiruv"),
    export: loc("Экспорт", "Eksport"),
    filters: loc("Фильтры", "Filtrlar"),
    all: loc("Все", "Barchasi"),
    reset: loc("Сбросить", "Tozalash"),
    today: loc("Сегодня", "Bugun"),
    clear: loc("Очистить", "Tozalash"),
    pickDate: loc("Выбрать дату", "Sanani tanlash"),
    fullName: loc("ФИО", "F.I.Sh."),
    latinName: loc("Имя латиницей", "Ism lotin harflarida"),
    minutesShort: loc("мин", "daq"),
    hoursShort: loc("ч", "soat"),
    save: loc("Сохранить", "Saqlash"),
    empty: loc("Пусто", "Bo‘sh"),
    nothingFound: loc("Ничего не найдено — попробуйте снять фильтры.", "Hech narsa topilmadi — filtrlarni olib tashlang."),
    noTasks: loc("Задач нет.", "Vazifalar yo‘q."),
    noApplications: loc("Заявок пока нет.", "Hozircha arizalar yo‘q."),
    perYear: loc("в год", "yiliga"),
    notSet: loc("не задан", "belgilanmagan"),
    notRequired: loc("не требуется", "talab qilinmaydi"),
    none: loc("нет", "yo‘q"),
    yes: loc("есть", "bor"),
    curator: loc("куратор", "kurator"),
    mail: loc("Почта", "Pochta"),
    notifications: loc("Уведомления", "Bildirishnomalar"),
    workspace: loc("Рабочее пространство", "Ish maydoni"),
    signInAs: loc("Войти как сотрудник", "Xodim sifatida kirish"),
    language: loc("Язык интерфейса", "Interfeys tili"),
    scopeTenant: loc("всё агентство", "butun agentlik"),
    scopeBranch: loc("свой филиал", "o‘z filiali"),
    scopeOwn: loc("только свои записи", "faqat o‘z yozuvlari"),
    accessDenied: loc("Раздел недоступен", "Bo‘lim mavjud emas"),
    notFoundTitle: loc("Запись не найдена", "Yozuv topilmadi"),
    notFoundHint: loc(
      "Её нет либо она вне вашей зоны видимости: система не показывает записи чужого агентства, филиала или коллеги.",
      "U mavjud emas yoki sizning ko‘rish doirangizdan tashqarida: tizim boshqa agentlik, filial yoki hamkasb yozuvlarini ko‘rsatmaydi.",
    ),
    toHome: loc("На главную", "Bosh sahifaga"),
    accessDeniedHint: loc(
      "У роли нет прав на этот модуль. Попросите директора агентства расширить доступ в разделе «Сотрудники».",
      "Bu rolda modulga huquq yo‘q. Agentlik direktoridan «Xodimlar» bo‘limida huquq berishini so‘rang.",
    ),
  },

  dashboard: {
    greeting: loc("Добрый день", "Xayrli kun"),
    date: loc("16 сентября 2026, среда", "2026-yil 16-sentabr, chorshanba"),
    activeApps: loc("активных заявок", "faol ariza"),
    weekDeadlines: loc("дедлайнов на неделе", "shu haftadagi muddat"),
    newApplication: loc("Новая заявка", "Yangi ariza"),
    tileStudents: loc("Студенты в работе", "Ishdagi talabalar"),
    tileStudentsHint: loc("всего в базе", "bazada jami"),
    tileApps: loc("Заявки в воронке", "Voronkadagi arizalar"),
    tileWithOffer: loc("с offer", "offer bilan"),
    tileOnVisa: loc("на визе", "vizada"),
    tileDeadlines: loc("Дедлайны ≤ 7 дней", "Muddatlar ≤ 7 kun"),
    tileNearest: loc("ближайший", "eng yaqini"),
    tileCalm: loc("всё спокойно", "hammasi joyida"),
    tileContracted: loc("Законтрактовано", "Shartnomalar summasi"),
    tilePaid: loc("оплачено", "to‘langan"),
    funnel: loc("Воронка заявок", "Arizalar voronkasi"),
    openBoard: loc("Открыть доску", "Doskani ochish"),
    nearestDeadlines: loc("Ближайшие дедлайны", "Eng yaqin muddatlar"),
    allDeadlines: loc("Все дедлайны", "Barcha muddatlar"),
    myTasks: loc("Мои задачи", "Mening vazifalarim"),
    allTasks: loc("Все задачи", "Barcha vazifalar"),
    feed: loc("Лента агентства", "Agentlik lentasi"),
    important: loc("важно", "muhim"),
    spotlightEyebrow: loc("Подбор вузов", "Universitet tanlash"),
    spotlightTitle: loc(
      "Соберите шорт-лист по TOPIK, бюджету, городу и направлению — за один проход по каталогу.",
      "TOPIK, byudjet, shahar va yo‘nalish bo‘yicha qisqa ro‘yxatni bir o‘tishda tuzing.",
    ),
    spotlightCta: loc("Открыть каталог", "Katalogni ochish"),
  },

  students: {
    passport: loc("Паспорт", "Pasport"),
    title: loc("Студенты", "Talabalar"),
    inScope: loc("в вашей зоне видимости", "sizning ko‘rish doirangizda"),
    scopeLabel: loc("область доступа", "kirish doirasi"),
    add: loc("Добавить студента", "Talaba qo‘shish"),
    filterLead: loc("Лиды", "Lidlar"),
    filterActive: loc("В работе", "Ishda"),
    filterEnrolled: loc("Зачислены", "Qabul qilingan"),
    filterPaused: loc("На паузе", "To‘xtatilgan"),
    filterLost: loc("Потеряны", "Yo‘qotilgan"),
    allCurators: loc("Все кураторы", "Barcha kuratorlar"),
    anyTopik: loc("Любой TOPIK", "Istalgan TOPIK"),
    searchBase: loc("Поиск по базе", "Baza bo‘yicha qidiruv"),
    colStudent: loc("Студент", "Talaba"),
    colProfile: loc("Профиль", "Profil"),
    colBudget: loc("Бюджет / год", "Byudjet / yil"),
    colGoal: loc("Цель", "Maqsad"),
    colCurator: loc("Куратор", "Kurator"),
    colDossier: loc("Досье", "Dosye"),
    colStatus: loc("Статус", "Holat"),
    needsGrant: loc("нужен грант", "grant kerak"),
    anyCity: loc("любой город", "istalgan shahar"),
    notChosen: loc("не выбрано", "tanlanmagan"),
    notDefined: loc("не определено", "aniqlanmagan"),
    applicationsShort: loc("заявок", "ariza"),
    call: loc("Позвонить", "Qo‘ng‘iroq"),
    write: loc("Написать", "Xat yozish"),
    pickUniversity: loc("Подобрать вуз", "Universitet tanlash"),
    birthDate: loc("Дата рождения", "Tug‘ilgan sana"),
    education: loc("Образование", "Ma’lumoti"),
    gradYear: loc("Год выпуска", "Bitirgan yili"),
    inBaseSince: loc("В базе с", "Bazada"),
    lastTouch: loc("Последний контакт", "Oxirgi aloqa"),
    portfolio: loc("Портфолио", "Portfolio"),
    topikValidUntil: loc("TOPIK действует до", "TOPIK amal qiladi"),
    noCertificate: loc("нет сертификата", "sertifikat yo‘q"),
    budgetPerYear: loc("Бюджет в год", "Yillik byudjet"),
    level: loc("Уровень", "Bosqich"),
    intake: loc("Набор", "Qabul"),
    cities: loc("Города", "Shaharlar"),
    fields: loc("Направления", "Yo‘nalishlar"),
    ownership: loc("Форма вуза", "Universitet shakli"),
    dorm: loc("Общежитие", "Yotoqxona"),
    dormNeeded: loc("нужно", "kerak"),
    dormNotNeeded: loc("не нужно", "kerak emas"),
    grant: loc("Грант", "Grant"),
    grantCritical: loc("критично", "juda muhim"),
    grantPreferred: loc("желательно", "ma’qul"),
    dossierTitle: loc("Досье документов", "Hujjatlar dosyesi"),
    verifiedOf: loc("проверено", "tekshirilgan"),
    applications: loc("Заявки", "Arizalar"),
    recommended: loc("Рекомендованные вузы", "Tavsiya etilgan universitetlar"),
    allUniversities: loc("Все вузы", "Barcha universitetlar"),
    relatedTasks: loc("Связанные задачи", "Bog‘liq vazifalar"),
    age: loc("лет", "yosh"),
    source: loc("источник", "manba"),
    fileMissing: loc("файл не загружен", "fayl yuklanmagan"),
    needsApostille: loc("нужен апостиль", "apostil kerak"),
    apostille: loc("апостиль", "apostil"),
  },

  applications: {
    title: loc("Заявки", "Arizalar"),
    count: loc("заявок", "ariza"),
    subtitle: loc(
      "воронка от первого звонка до вылета",
      "birinchi qo‘ng‘iroqdan jo‘nashgacha bo‘lgan voronka",
    ),
    allStages: loc("Все этапы", "Barcha bosqichlar"),
    collectingShort: loc("Сбор документов", "Hujjat yig‘ish"),
    submittedShort: loc("Поданные", "Topshirilgan"),
    visaShort: loc("На визе", "Vizada"),
    allIntakes: loc("Все наборы", "Barcha qabullar"),
    onlyUrgent: loc("Только срочные", "Faqat shoshilinch"),
    inSelection: loc("заявок в выборке", "tanlovdagi ariza"),
    dossier: loc("Досье", "Dosye"),
    onStage: loc("на этапе", "bosqichda"),
    studentCard: loc("Карточка студента", "Talaba kartasi"),
    nextStage: loc("Перевести на следующий этап", "Keyingi bosqichga o‘tkazish"),
    docsOfApplication: loc("Документы по заявке", "Ariza hujjatlari"),
    fitTitle: loc("Сходимость с требованиями вуза", "Universitet talablariga moslik"),
    universityCard: loc("Карточка вуза", "Universitet kartasi"),
    fullYearCost: loc("полная стоимость года", "yillik to‘liq narx"),
    tasksOfApplication: loc("Задачи по заявке", "Ariza vazifalari"),
    application: loc("Заявка", "Ariza"),
    priority: loc("Приоритет", "Muhimlik"),
    created: loc("Создана", "Yaratilgan"),
    deadline: loc("Дедлайн", "Muddat"),
    contract: loc("Договор", "Shartnoma"),
    paid: loc("Оплачено", "To‘langan"),
    university: loc("Вуз", "Universitet"),
    city: loc("Город", "Shahar"),
    program: loc("Программа", "Dastur"),
    yearPrice: loc("Стоимость года", "Yillik narx"),
    requiredTopik: loc("Требуемый TOPIK", "Talab qilinadigan TOPIK"),
    curatorNote: loc("Заметка куратора", "Kurator izohi"),
    student: loc("Студент", "Talaba"),
    intake: loc("набор", "qabul"),
  },

  documents: {
    title: loc("Документы", "Hujjatlar"),
    folders: loc("папок студентов", "talaba papkasi"),
    documents: loc("документов", "hujjat"),
    needAttention: loc("требуют внимания", "e’tibor talab qiladi"),
    upload: loc("Загрузить документ", "Hujjat yuklash"),
    uploadFile: loc("Загрузить файл", "Fayl yuklash"),
    allFolders: loc("Все папки", "Barcha papkalar"),
    tabProblem: loc("Требуют внимания", "E’tibor talab qiladi"),
    tabExpiring: loc("Истекает срок", "Muddati tugayapti"),
    searchStudent: loc("Поиск по студенту", "Talaba bo‘yicha qidiruv"),
    noFolders: loc("Папок нет", "Papkalar yo‘q"),
    dossierOf: loc("Досье", "Dosye"),
    verified: loc("проверено", "tekshirilgan"),
    updated: loc("обновлено", "yangilangan"),
    until: loc("до", "gacha"),
  },

  tasks: {
    title: loc("Задачи", "Vazifalar"),
    inProgress: loc("в работе", "ishda"),
    subtitle: loc(
      "руководитель ставит задачу — исполнитель видит её у себя и в дедлайнах",
      "rahbar vazifa qo‘yadi — ijrochi uni o‘zida va muddatlarda ko‘radi",
    ),
    create: loc("Новая задача", "Yangi vazifa"),
    onlyMine: loc("Только мои", "Faqat meniki"),
    allAssignees: loc("Все исполнители", "Barcha ijrochilar"),
    overdue: loc("просрочено", "kechikkan"),
    highPriority: loc("высокий приоритет", "yuqori muhimlik"),
  },

  deadlines: {
    title: loc("Дедлайны", "Muddatlar"),
    events: loc("событий", "hodisa"),
    overdue: loc("просрочено", "kechikkan"),
    subtitle: loc(
      "собираются автоматически из заявок, документов и задач — вручную ничего не дублируется",
      "arizalar, hujjatlar va vazifalardan avtomatik yig‘iladi — qo‘lda takrorlash shart emas",
    ),
    toCalendar: loc("В календарь (.ics)", "Kalendarga (.ics)"),
    groupOverdue: loc("Просрочено", "Kechikkan"),
    groupToday: loc("Сегодня и завтра", "Bugun va ertaga"),
    groupWeek: loc("Ближайшие 7 дней", "Yaqin 7 kun"),
    groupMonth: loc("8–30 дней", "8–30 kun"),
    groupLater: loc("Позже", "Keyinroq"),
  },

  universities: {
    title: loc("Каталог вузов", "Universitetlar katalogi"),
    country: loc("Корея", "Koreya"),
    universities: loc("вузов", "universitet"),
    programs: loc("программ", "dastur"),
    exportShortlist: loc("Выгрузить шорт-лист", "Qisqa ro‘yxatni yuklash"),
    add: loc("Добавить вуз", "Universitet qo‘shish"),
    draftBanner: loc(
      "Этап 1: структура и фильтры. Карточки заполнены демо-данными и помечены как «черновик». На этапе 2 записи заполняются с официальных страниц вузов и файлов admission guideline, после сверки карточка получает статус «проверено» и дату источника.",
      "1-bosqich: tuzilma va filtrlar. Kartalar demo ma’lumotlar bilan to‘ldirilgan va «qoralama» deb belgilangan. 2-bosqichda ma’lumotlar universitetlarning rasmiy sahifalari va admission guideline fayllaridan olinadi, tekshiruvdan so‘ng karta «tekshirilgan» maqomini oladi.",
    ),
    pickForStudent: loc("Подобрать под студента", "Talaba uchun tanlash"),
    applyPreferences: loc("Фильтровать по профилю", "Profil bo‘yicha filtrlash"),
    preferencesHint: loc(
      "Профиль студента сортирует список и объясняет каждый вуз. Включите, чтобы жёстко отсечь неподходящие.",
      "Talaba profili ro‘yxatni saralaydi va har bir universitetni izohlaydi. Mos kelmaganlarni butunlay olib tashlash uchun yoqing.",
    ),
    chooseStudent: loc("— выбрать студента —", "— talabani tanlang —"),
    budget: loc("бюджет", "byudjet"),
    cityAny: loc("город любой", "shahar ixtiyoriy"),
    universityName: loc("Название вуза", "Universitet nomi"),
    city: loc("Город", "Shahar"),
    ownership: loc("Форма собственности", "Mulkchilik shakli"),
    field: loc("Направление", "Yo‘nalish"),
    degree: loc("Уровень обучения", "Ta’lim bosqichi"),
    studentTopik: loc("TOPIK студента", "Talabaning TOPIK darajasi"),
    studentIelts: loc("IELTS студента", "Talabaning IELTS bali"),
    budgetPerYear: loc("Бюджет на год", "Yillik byudjet"),
    intake: loc("Набор", "Qabul"),
    conditions: loc("Условия", "Shartlar"),
    hasDorm: loc("Есть общежитие", "Yotoqxona bor"),
    grantFrom: loc("Грант от 50%", "Grant 50% dan"),
    languageCenter: loc("Языковой центр", "Til markazi"),
    visaGradeA: loc("Визовый рейтинг A", "Viza reytingi A"),
    englishTaught: loc("Есть английский трек", "Ingliz tili treki bor"),
    deadlineSoon: loc("Дедлайн", "Muddat"),
    any: loc("Любой", "Istalgan"),
    notImportant: loc("Не важно", "Farqi yo‘q"),
    noCertificate: loc("Нет сертификата", "Sertifikat yo‘q"),
    upTo: loc("до", "gacha"),
    found: loc("Найдено", "Topildi"),
    sortedByMatch: loc("отсортировано по совпадению с профилем", "profil bilan moslikka ko‘ra saralangan"),
    draft: loc("черновик данных", "ma’lumot qoralamasi"),
    verified: loc("проверено", "tekshirilgan"),
    tuitionPerYear: loc("Обучение в год", "Yillik o‘qish"),
    dorm: loc("Общежитие", "Yotoqxona"),
    requirements: loc("Требования", "Talablar"),
    morePrograms: loc("программ", "dastur"),
    noResults: loc("Под эти условия вузов нет", "Bu shartlarga mos universitet yo‘q"),
    noResultsHint: loc(
      "Снимите часть фильтров — обычно первым мешает бюджет или уровень TOPIK.",
      "Ba’zi filtrlarni olib tashlang — odatda byudjet yoki TOPIK darajasi to‘sqinlik qiladi.",
    ),
    inCountry: loc("в стране", "mamlakatda"),
    noRank: loc("без рейтинга", "reytingsiz"),
    founded: loc("основан в", "tashkil etilgan"),
    compare: loc("Сравнить", "Solishtirish"),
    addToShortlist: loc("Добавить в шорт-лист", "Qisqa ro‘yxatga qo‘shish"),
    programsTitle: loc("Программы", "Dasturlar"),
    languageOfStudy: loc("язык", "til"),
    whoFits: loc("Кому из базы подходит", "Bazadan kimga mos keladi"),
    noFits: loc(
      "Подходящих студентов в вашей зоне видимости нет.",
      "Ko‘rish doirangizda mos talabalar yo‘q.",
    ),
    ourApplications: loc("Наши заявки в этот вуз", "Bu universitetga arizalarimiz"),
    bankBalance: loc("Счёт в банке", "Bankdagi hisob"),
    gradWithin: loc("Срок после выпуска", "Bitirgandan keyingi muddat"),
    notLimited: loc("не ограничен", "cheklanmagan"),
    yearsUpTo: loc("до", "gacha"),
    years: loc("лет", "yil"),
    admissionFee: loc("Вступительный взнос", "Ariza to‘lovi"),
    scholarshipUpTo: loc("Грант", "Grant"),
    visaStatus: loc("Визовый статус", "Viza maqomi"),
    intakes: loc("Наборы", "Qabullar"),
    sourceTitle: loc("Источник данных", "Ma’lumot manbai"),
    status: loc("Статус", "Holat"),
    updatedAt: loc("Обновлено", "Yangilangan"),
    guideline: loc("Admission guideline", "Admission guideline"),
    notLinked: loc("не привязан", "biriktirilmagan"),
    sourceHint: loc(
      "На этапе 2 сюда подключается разбор официальной страницы вуза и PDF с правилами приёма: система сверяет цифры и ставит дату проверки.",
      "2-bosqichda bu yerga universitetning rasmiy sahifasi va qabul qoidalari PDF fayli ulanadi: tizim raqamlarni solishtirib, tekshiruv sanasini qo‘yadi.",
    ),
  },

  shortlist: {
    add: loc("В шорт-лист", "Qisqa ro‘yxatga"),
    added: loc("В шорт-листе", "Ro‘yxatda"),
    title: loc("Шорт-лист", "Qisqa ro‘yxat"),
    count: loc("в шорт-листе", "qisqa ro‘yxatda"),
    compare: loc("Сравнить", "Solishtirish"),
    clear: loc("Очистить", "Tozalash"),
    limit: loc("максимум 6 вузов", "eng ko‘pi 6 ta universitet"),
    empty: loc("Шорт-лист пуст", "Qisqa ro‘yxat bo‘sh"),
    emptyHint: loc(
      "Откройте каталог, отфильтруйте вузы под профиль студента и добавьте подходящие — здесь они встанут рядом для сравнения.",
      "Katalogni oching, universitetlarni talaba profiliga moslab filtrlang va mos kelganlarini qo‘shing — bu yerda ular yonma-yon solishtiriladi.",
    ),
    forStudent: loc("для студента", "talaba uchun"),
    compareTitle: loc("Сравнение вузов", "Universitetlarni solishtirish"),
    backToCatalog: loc("К каталогу", "Katalogga"),
    criterion: loc("Критерий", "Mezon"),
    verdict: loc("Вердикт подбора", "Tanlov xulosasi"),
    yearCost: loc("Полная стоимость года", "Yillik to‘liq narx"),
    englishTaught: loc("Программы на английском", "Ingliz tilidagi dasturlar"),
    deadline: loc("Дедлайн подачи", "Topshirish muddati"),
    noDeadline: loc("набор закрыт", "qabul yopilgan"),
    selectStudent: loc("Студент", "Talaba"),
    withoutStudent: loc("Без студента", "Talabasiz"),
  },

  finance: {
    title: loc("Финансы", "Moliya"),
    contractsInWork: loc("договоров в работе", "ishdagi shartnoma"),
    subtitle: loc(
      "суммы договоров с семьями в сумах; стоимость обучения в вузе считается отдельно",
      "oilalar bilan shartnoma summalari so‘mda; universitet o‘qish narxi alohida hisoblanadi",
    ),
    exportRegistry: loc("Выгрузить реестр", "Reestrni yuklash"),
    contracted: loc("Законтрактовано", "Shartnomalar summasi"),
    paid: loc("Оплачено", "To‘langan"),
    ofContracts: loc("от суммы договоров", "shartnoma summasidan"),
    receivable: loc("Дебиторка", "Qarzdorlik"),
    closedWon: loc("Закрыто успешно", "Muvaffaqiyatli yopilgan"),
    received: loc("получено", "olingan"),
    byManager: loc("По менеджерам", "Menejerlar bo‘yicha"),
    contractsShort: loc("дог.", "shart."),
    outOf: loc("из", "dan"),
    contracts: loc("Договоры", "Shartnomalar"),
    colStage: loc("Этап", "Bosqich"),
    colRest: loc("Остаток", "Qoldiq"),
    rate: loc("курс", "kurs"),
  },

  team: {
    openCard: loc("Открыть карточку", "Kartani ochish"),
    status: loc("Статус", "Holat"),
    personal: loc("Личные данные", "Shaxsiy ma’lumotlar"),
    birthDate: loc("День рождения", "Tug‘ilgan kun"),
    phoneWork: loc("Рабочий телефон", "Ish telefoni"),
    phonePersonal: loc("Второй номер", "Ikkinchi raqam"),
    hiredAt: loc("Принят на работу", "Ishga qabul qilingan"),
    department: loc("Подразделение", "Bo‘lim"),
    workdayToday: loc("Рабочий день сегодня", "Bugungi ish kuni"),
    dealsShort: loc("сделки", "bitim"),
    title: loc("Сотрудники", "Xodimlar"),
    people: loc("человек", "kishi"),
    seats: loc("мест по тарифу", "tarif bo‘yicha o‘rin"),
    of: loc("из", "dan"),
    subtitle: loc(
      "роль определяет и права, и зону видимости данных",
      "rol ham huquqni, ham ma’lumot ko‘rish doirasini belgilaydi",
    ),
    invite: loc("Пригласить", "Taklif qilish"),
    active: loc("активен", "faol"),
    invited: loc("приглашён", "taklif qilingan"),
    suspended: loc("заблокирован", "bloklangan"),
    studentsShort: loc("студентов", "talaba"),
    applicationsShort: loc("заявок", "ariza"),
    tasksShort: loc("задач", "vazifa"),
    inSystemSince: loc("в системе с", "tizimda"),
    lastSeen: loc("был", "oxirgi marta"),
    matrix: loc("Матрица прав", "Huquqlar matritsasi"),
    role: loc("Роль", "Rol"),
    levelFull: loc("полный", "to‘liq"),
    levelEdit: loc("правка", "tahrir"),
    levelRead: loc("чтение", "o‘qish"),
  },

  settings: {
    title: loc("Настройки агентства", "Agentlik sozlamalari"),
    seats: loc("мест", "o‘rin"),
    saveChanges: loc("Сохранить изменения", "O‘zgarishlarni saqlash"),
    addressTitle: loc("Адрес системы", "Tizim manzili"),
    addressHint: loc(
      "Каждое агентство работает на своём поддомене — сотрудники и клиенты видят только его.",
      "Har bir agentlik o‘z subdomenida ishlaydi — xodimlar va mijozlar faqat uni ko‘radi.",
    ),
    platformSubdomain: loc("Поддомен платформы", "Platforma subdomeni"),
    willOpenAt: loc("Система откроется по адресу", "Tizim shu manzilda ochiladi"),
    unavailable: loc("Недоступно", "Band"),
    ownDomain: loc("Собственный домен агентства", "Agentlikning o‘z domeni"),
    domainNotConnected: loc("домен не подключён", "domen ulanmagan"),
    domainVerified: loc("DNS проверен, сертификат выпущен", "DNS tekshirildi, sertifikat berildi"),
    domainPending: loc("ждём проверки DNS", "DNS tekshiruvi kutilmoqda"),
    domainCanConnect: loc(
      "можно подключить свой домен вместо поддомена",
      "subdomen o‘rniga o‘z domeningizni ulash mumkin",
    ),
    dnsTitle: loc("Что добавить в DNS домена агентства:", "Agentlik domeni DNS’iga qo‘shiladigan yozuvlar:"),
    tlsHint: loc(
      "Сертификат TLS выпускается автоматически после проверки записи.",
      "TLS sertifikati yozuv tekshirilgandan so‘ng avtomatik beriladi.",
    ),
    currentHost: loc("Текущий хост запроса", "Joriy so‘rov xosti"),
    isolation: loc("Изоляция данных", "Ma’lumot izolyatsiyasi"),
    isolationValue: loc(
      "строгая: запрос без совпадающего арендатора не видит ни одной записи",
      "qat’iy: mos ijarachisiz so‘rov birorta yozuvni ko‘rmaydi",
    ),
    rolesTitle: loc("Роли и доступы", "Rollar va huquqlar"),
    modules: loc("модулей", "modul"),
    integrations: loc("Интеграции", "Integratsiyalar"),
    stage2: loc("этап 2", "2-bosqich"),
    agency: loc("Агентство", "Agentlik"),
    name: loc("Название", "Nomi"),
    legalName: loc("Юридическое лицо", "Yuridik shaxs"),
    monogram: loc("Монограмма", "Monogramma"),
    interfaceLanguage: loc("Язык интерфейса по умолчанию", "Standart interfeys tili"),
    currency: loc("Валюта договоров", "Shartnoma valyutasi"),
    usdRate: loc("Курс доллара", "Dollar kursi"),
    rateHint: loc(
      "Курс применяется только для пересчёта стоимости обучения: вузы публикуют цены в долларах, семья считает в сумах.",
      "Kurs faqat o‘qish narxini qayta hisoblash uchun ishlatiladi: universitetlar narxni dollarda e’lon qiladi, oila so‘mda hisoblaydi.",
    ),
    inSystemSince: loc("В системе с", "Tizimda"),
    plan: loc("Тариф", "Tarif"),
    seatsUsed: loc("рабочих мест занято", "ish o‘rni band"),
    addSeats: loc("Добавить места", "O‘rin qo‘shish"),
    branches: loc("Филиалы", "Filiallar"),
    addBranch: loc("Добавить филиал", "Filial qo‘shish"),
  },

  integrations: {
    telegram: loc("Telegram-бот для лидов", "Lidlar uchun Telegram-bot"),
    telegramHint: loc("заявка из бота сразу в воронку", "botdan ariza to‘g‘ridan-to‘g‘ri voronkaga"),
    smtp: loc("Почта агентства (SMTP)", "Agentlik pochtasi (SMTP)"),
    smtpHint: loc("письма студентам с домена агентства", "talabalarga agentlik domenidan xatlar"),
    storage: loc("Хранилище документов", "Hujjatlar ombori"),
    storageHint: loc("S3-совместимое, с версиями файлов", "S3-mos, fayl versiyalari bilan"),
    catalog: loc("Импорт каталога вузов", "Universitetlar katalogini import qilish"),
    catalogHint: loc("разбор admission guideline", "admission guideline tahlili"),
  },

  crm: {
    leads: loc("Лиды", "Lidlar"),
    deals: loc("Сделки", "Bitimlar"),
    contacts: loc("Контакты", "Kontaktlar"),
    lead: loc("Лид", "Lid"),
    deal: loc("Сделка", "Bitim"),
    contact: loc("Контакт", "Kontakt"),
    newLead: loc("Новый лид", "Yangi lid"),
    newDeal: loc("Новая сделка", "Yangi bitim"),
    newContact: loc("Новый контакт", "Yangi kontakt"),
    convert: loc("Конвертировать", "Konvertatsiya qilish"),
    converted: loc("Конвертирован", "Konvertatsiya qilingan"),
    convertHint: loc(
      "Создаст контакт и первую сделку, лид закроется и останется в истории.",
      "Kontakt va birinchi bitim yaratiladi, lid yopiladi va tarixda qoladi.",
    ),
    source: loc("Источник", "Manba"),
    channel: loc("Канал", "Kanal"),
    comment: loc("Комментарий", "Izoh"),
    inWork: loc("в работе", "ishda"),
    junkReason: loc("Причина", "Sabab"),
    dealsOfContact: loc("Сделки контакта", "Kontakt bitimlari"),
    noDeals: loc("Сделок пока нет", "Hozircha bitimlar yo‘q"),
    duplicateFound: loc("Найден дубль", "Dublikat topildi"),
    duplicateByPhone: loc("по номеру телефона", "telefon raqami bo‘yicha"),
    duplicateByEmail: loc("по email", "email bo‘yicha"),
    duplicateByPassport: loc("по номеру паспорта", "pasport raqami bo‘yicha"),
    duplicateHint: loc(
      "Такой человек уже есть в системе. Новая запись не создаётся — обращение уходит в существующую карточку.",
      "Bunday odam tizimda bor. Yangi yozuv yaratilmaydi — murojaat mavjud kartaga tushadi.",
    ),
    openExisting: loc("Открыть карточку", "Kartani ochish"),
    checkDuplicate: loc("Проверить дубль", "Dublikatni tekshirish"),
    phone: loc("Телефон", "Telefon"),
    createdFromLead: loc("Создан из лида", "Liddan yaratilgan"),
    dealsShort: loc("сделок", "bitim"),
    contactsTitle: loc("Контакты", "Kontaktlar"),
    contactsSubtitle: loc(
      "один человек — одна карточка: повторные обращения падают в её историю",
      "bir odam — bitta karta: takroriy murojaatlar uning tarixiga tushadi",
    ),
    junk: loc("Некачественный", "Sifatsiz"),
    backToLeads: loc("К лидам", "Lidlarga"),
    backToDeals: loc("К сделкам", "Bitimlarga"),
    backToContacts: loc("К контактам", "Kontaktlarga"),
    stage: loc("Стадия", "Bosqich"),
    edit: loc("Изменить", "O‘zgartirish"),
    mainFields: loc("Основные поля", "Asosiy maydonlar"),
    contract: loc("Договор", "Shartnoma"),
    paid: loc("Оплачено", "To‘langan"),
  },

  pipelines: {
    title: loc("Воронки", "Voronkalar"),
    subtitle: loc(
      "стадии, их порядок и цвета — то, как агентство видит свою работу",
      "bosqichlar, tartibi va ranglari — agentlik ishini qanday ko‘rishi",
    ),
    stages: loc("Стадии", "Bosqichlar"),
    rename: loc("Название стадии", "Bosqich nomi"),
    color: loc("Цвет", "Rang"),
    hexCode: loc("Код цвета", "Rang kodi"),
    editStage: loc("Изменить стадию", "Bosqichni o‘zgartirish"),
    cardView: loc("Карточка просмотра", "Ko‘rish kartasi"),
    cardViewHint: loc(
      "Какие поля показывать на карточке канбана и в каком порядке.",
      "Kanban kartasida qaysi maydonlar va qanday tartibda ko‘rsatilsin.",
    ),
    fieldPhone: loc("Телефон", "Telefon"),
    fieldSource: loc("Источник", "Manba"),
    fieldComment: loc("Комментарий", "Izoh"),
    fieldUniversity: loc("Вуз", "Universitet"),
    fieldProgram: loc("Программа", "Dastur"),
    fieldIntake: loc("Набор", "Qabul"),
    fieldDossier: loc("Готовность досье", "Dosye tayyorligi"),
    fieldAmount: loc("Сумма договора", "Shartnoma summasi"),
    fieldDeadline: loc("Дедлайн", "Muddat"),
    fieldOwner: loc("Ответственный", "Mas’ul"),
    dragHint: loc("Перетащите карточку на другую стадию", "Kartani boshqa bosqichga torting"),
    pipeline: loc("Воронка", "Voronka"),
    viewKanban: loc("Канбан", "Kanban"),
    viewList: loc("Список", "Ro‘yxat"),
    moved: loc("Карточка перенесена", "Karta ko‘chirildi"),
  },

  channels: {
    title: loc("Каналы продаж", "Sotuv kanallari"),
    subtitle: loc(
      "откуда приходят обращения: каждое новое попадает в лиды",
      "murojaatlar qayerdan keladi: har biri lidlarga tushadi",
    ),
    connected: loc("Подключён", "Ulangan"),
    pending: loc("Ожидает подключения", "Ulanish kutilmoqda"),
    off: loc("Отключён", "O‘chirilgan"),
    connect: loc("Подключить", "Ulash"),
    disconnect: loc("Отключить", "O‘chirish"),
    leadsPerMonth: loc("лидов в месяц", "oyiga lid"),
    instagram: loc("Instagram Direct", "Instagram Direct"),
    telegram: loc("Telegram-бот", "Telegram-bot"),
    email: loc("Почта агентства", "Agentlik pochtasi"),
    phone: loc("Телефония", "Telefoniya"),
    stage2: loc(
      "Интерфейс подключения готов; обмен сообщениями включается на этапе интеграций.",
      "Ulanish interfeysi tayyor; xabar almashish integratsiya bosqichida yoqiladi.",
    ),
  },

  timeline: {
    title: loc("История", "Tarix"),
    tabActivity: loc("Дело", "Ish"),
    tabComment: loc("Комментарий", "Izoh"),
    tabMessage: loc("Сообщение", "Xabar"),
    tabTask: loc("Задача", "Vazifa"),
    tabTelegram: loc("Telegram", "Telegram"),
    tabMore: loc("Ещё", "Yana"),
    placeholder: loc("Что нужно сделать", "Nima qilish kerak"),
    add: loc("Добавить", "Qo‘shish"),
    done: loc("Выполнено", "Bajarildi"),
    dueTo: loc("Сделать до", "Bajarish muddati"),
    empty: loc("Событий пока нет", "Hozircha hodisalar yo‘q"),
  },

  projects: {
    title: loc("Проекты", "Loyihalar"),
    members: loc("Участники", "Ishtirokchilar"),
    manager: loc("Руководитель", "Rahbar"),
    due: loc("Срок", "Muddat"),
    tasksInProject: loc("задач в проекте", "loyihadagi vazifa"),
    statusActive: loc("Активен", "Faol"),
    statusDone: loc("Завершён", "Yakunlangan"),
    statusPaused: loc("На паузе", "To‘xtatilgan"),
    reports: loc("Отчёты", "Hisobotlar"),
    templates: loc("Шаблоны", "Shablonlar"),
    checklist: loc("Чек-лист", "Ro‘yxat"),
    useTemplate: loc("Создать по шаблону", "Shablon bo‘yicha yaratish"),
    completed: loc("выполнено", "bajarilgan"),
    overdueTasks: loc("просрочено", "kechikkan"),
  },

  structure: {
    title: loc("Структура компании", "Kompaniya tuzilmasi"),
    subtitle: loc(
      "подразделения и руководители; сотрудника можно перенести в другой отдел",
      "bo‘limlar va rahbarlar; xodimni boshqa bo‘limga ko‘chirish mumkin",
    ),
    head: loc("Руководитель", "Rahbar"),
    employees: loc("сотрудников", "xodim"),
    moveHere: loc("Перенести сюда", "Bu yerga ko‘chirish"),
  },

  workday: {
    start: loc("Начать рабочий день", "Ish kunini boshlash"),
    end: loc("Завершить рабочий день", "Ish kunini yakunlash"),
    breakStart: loc("Перерыв", "Tanaffus"),
    breakEnd: loc("Вернуться к работе", "Ishga qaytish"),
    working: loc("Рабочий день идёт", "Ish kuni davom etmoqda"),
    onBreak: loc("Перерыв", "Tanaffus"),
    notStarted: loc("Рабочий день не начат", "Ish kuni boshlanmagan"),
    startedAt: loc("Начат в", "Boshlandi"),
    todayTotal: loc("Сегодня отработано", "Bugun ishlangan"),
    myProfile: loc("Мой профиль", "Mening profilim"),
    logout: loc("Выйти", "Chiqish"),
  },

  staffReports: {
    title: loc("Отчётность сотрудников", "Xodimlar hisoboti"),
    subtitle: loc(
      "часы считаются из отметок «начать» и «завершить рабочий день»",
      "soatlar «boshlash» va «yakunlash» belgilaridan hisoblanadi",
    ),
    employee: loc("Сотрудник", "Xodim"),
    days: loc("Дней", "Kunlar"),
    hours: loc("Часов", "Soat"),
    average: loc("Средний день", "O‘rtacha kun"),
    breaks: loc("Перерывы", "Tanaffuslar"),
    late: loc("Опозданий", "Kechikishlar"),
    today: loc("Сегодня", "Bugun"),
    week: loc("Неделя", "Hafta"),
    month: loc("Месяц", "Oy"),
    stillWorking: loc("на работе", "ishda"),
    noData: loc("Отметок пока нет", "Belgilar yo‘q"),
  },

  admin: {
    title: loc("Администрирование", "Boshqaruv"),
    users: loc("Пользователи", "Foydalanuvchilar"),
    permissions: loc("Права доступа", "Kirish huquqlari"),
    portal: loc("Настройки портала", "Portal sozlamalari"),
    permissionsCount: loc("Роли и разделы", "Rollar va bo‘limlar"),
    crmSettings: loc("Настройки CRM", "CRM sozlamalari"),
    permissionsHint: loc(
      "Матрица прав редактируется прямо здесь: изменения сразу влияют на меню и данные сотрудников.",
      "Huquqlar matritsasi shu yerda tahrirlanadi: o‘zgarishlar darhol menyuga ta’sir qiladi.",
    ),
    module: loc("Раздел", "Bo‘lim"),
    scope: loc("Зона видимости", "Ko‘rish doirasi"),
    invite: loc("Пригласить", "Taklif qilish"),
    block: loc("Заблокировать", "Bloklash"),
    unblock: loc("Разблокировать", "Blokdan chiqarish"),
    changeRole: loc("Сменить роль", "Rolni o‘zgartirish"),
    seats: loc("мест по тарифу", "tarif bo‘yicha o‘rin"),
    auditLog: loc("Журнал действий", "Harakatlar jurnali"),
  },

  edition: {
    notIncluded: loc(
      "Модуль не входит в вашу версию продукта. Он включается вместе с версией CRM — вместе со всей работой по студентам: заявки, документы, задачи и сроки.",
      "Modul sizning mahsulot versiyangizga kirmaydi. U CRM versiyasi bilan birga ochiladi: arizalar, hujjatlar, vazifalar va muddatlar.",
    ),
    yourEdition: loc("Ваша версия", "Sizning versiyangiz"),
    upgrade: loc("Подключить версию", "Versiyani ulash"),
    edition: loc("Версия продукта", "Mahsulot versiyasi"),
    includedModules: loc("модулей включено", "modul yoqilgan"),
    roadmap: loc("Дорожная карта", "Yo‘l xaritasi"),
    current: loc("текущая", "joriy"),
    next: loc("следующая", "keyingi"),
    later: loc("позже", "keyinroq"),
  },

  plans: {
    trial: loc("Пробный период", "Sinov davri"),
    standard: loc("Standard", "Standard"),
    pro: loc("Pro", "Pro"),
    enterprise: loc("Enterprise", "Enterprise"),
  },
};
